sudo: false
language: ruby
cache: bundler
rvm:
#- 2.1
#- 2.1.1
- 2.1.5

install:
  # Install Jekyll and dependencies
  - bundle install

script:
  - bundle exec jekyll build

before_script:
  

after_success:
  - rsync -a $build_url $user@$host:$production_url --delete

notifications:
  email: false
