sudo: false
language: ruby
cache: bundler
rvm:
#- 2.1
#- 2.1.1
- 2.1.5

install:
  # Install Jekyll and dependencies
  - bundle install

script:
  - bundle exec jekyll build --drafts

notifications:
  email: false
