sudo: false
language: ruby
cache: bundler

# safelist
branches:
  only:
  - master
  - stable

rvm:
  - 2.1.5

install:
  - bundle install

script:
  - bundle exec jekyll build

after_success:
    - openssl aes-256-cbc -K $encrypted_11178bb4d22b_key -iv $encrypted_11178bb4d22b_iv -in .travis/aem_deploy_key.enc -out aem_deploy_key -d && chmod 600 aem_deploy_key

    -  rsync -arve "ssh -o StrictHostKeyChecking=no -i aem_deploy_key" $build_url $user@$host:$production_url --delete

notifications:
  email: false
  slack:
    secure: BILQ68hwb2u37g69i3RKk0nfBR1tcRndqurpKAhEu1HgaTK7bQkVeUADYjAZ0doGMJARuytSihI6DehggytOoO4M7hGZRtyUZx1zod3C0US+Ee8TkVucpHhIWxLkcYVU1aceC9rnjFWYzzBbNA4Fk/mi79fotZ7/h5fUMdUuI/iUycu/mD/3WaneDxse6yCnliIdun4Eg1RX4kd+NUbDjNPxAbZkXqpMd7Mtcw8rY0vJZ2lg3Ab9aUzRDv2XNlQC/XW6uhNcmjwaJ2fY915LZHgVLqMFBCfP50SlVgPTdI2QpYa0sMieh30XqGYeTE8J9+frephV8vF6T2jTkuYbt5EpmQ++j5zTcD6cbr/kuqK678HMa5TsDWmKIVjWv3C6kC9D4K6dGGZIVPGIWodu0QVnMJ1EVQsD4odGbUf3zdBZ5DdIps5aj9GsoFuNBh79aUXwqDrBYkqsszMHkfpE8ewUmI6CP6idGrWsvLZ1MswiA6o1UFx2+FICp/8IdMHcyFlz6zy6JDsYtbjsOgOD6GZsbCrpjNiiW5+FUjIrpej+wzTXD1o1QAlDVNTLyTgJHnRNiNbb2jK+CtPUgSucPna9PGx8Ksv3drcYjiwiBck/qBRC2ttYY76ZU2pP/RQ7HXNCSQdmY0J6xq5+kAUL3f5liHWHXTF2hPopmZ1zLlo=
