# Site settings
title: aethermonolog
email: mail@aethermonolog.de
description: "Musiker Kai"
baseurl: ""
url: "http://aethermonolog.de"
paginate: 5
paginate_path: "posts/:num"

# Build settings
markdown: kramdown
permalink: pretty

# Podcast settings
lang: en
author: David Darnes and Benjamin Reid

# Site owner
owner:
  name: Kai Birkenfeld
  bio:
  avatar:
  email: mail@dyscribe.com
  disqus-shortname: dyscribe
  twitter: dyscribe
  github: dyscribe
  flattr: dyscribe
  google:
    plus: +KaiBirkenfeld
    verify:

## podlove-web-palyer ##########################################################
poster: /img/logo-360x360.png
alwaysShowHours: true
startVolume: 0.8
width: auto
summaryVisible: false
timecontrolsVisible: false
chaptersVisible: true
sharebuttonsVisible: false


# Jekyll plugins
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-paginate

jekyll-mentions: https://twitter.com
