# Global site configurations

destination: ../html/aethermonolog.de
title: aethermonolog
email: moin@aethermonolog.de
description: "Monologe aus dem Kopf eines Musikers: Was inspiriert? Was blockiert? Was funktioniert? Eine Dokumentation musikalischer Schaffensprozesse."
subtitle: "Lamento ergo sum."
paginate: 1
paginate_path: "posts/:num"
baseurl: ""

# Switch between production and local development
url: http://aethermonolog.de
# url: http://localhost:4000

include: [".htaccess"]

exclude: ["lib", "config.rb", "gulpfile.js", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Build settings
permalink: none
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed

# Podcast settings
lang: de-DE
author: Kai Birkenfeld
copyright: "&#x2117; &amp; &#xA9; 2015"

# Site owner
owner:
  name: Kai Birkenfeld
  bio:
  avatar: /images/profile.jpg
  email: moin@aethermonolog.de
  twitter: aethermonolog
  facebook: Klartexter
  github: dyscribe
  flattr: dyscribe
  disqus: aethermonolog
  google:
    plus: +KaiBirkenfeld
    verify: XIwbHY2nAqd1Azf8Z3yHwuv1-k8FUlnnm9xQIxJsojQ

# Jekyll plugins
gems: [jekyll-mentions, jekyll-redirect-from, jekyll-paginate, jekyll-sitemap, jekyll-sass-converter]
