# Global site configurations

destination: ../html/aethermonolog.de
title: Aethermonolog Musik Podcast
tagline: Aethermonolog Podcast
email: moin@aethermonolog.de
description: "Der wöchentliche Podcast über Musikproduktion, Songwriting, Beatmaking und Audio Produktion. Tipps und Tricks für das Homestudio, Gear Reviews, Erfahrungsberichte und Interviews mit Experten aus verschiedenen Bereichen der Audio und Musikindustrie. Mehr auf www.aethermonolog.de"
seo: "Der wöchentliche Podcast über Musikproduktion, Songwriting und Homerecording. Tipps, Tricks und Interviews über Audio und Musik machen. Jetzt reinhören!"
subtitle: "Lamento ergo sum."
paginate: 5
paginate_path: "posts/:num"
baseurl: ""

# Switch between production and local development
url: https://aethermonolog.de
http-url: http://aethermonolog.de
# url: http://localhost:4000

include: [".htaccess"]

exclude: ["lib", "config.rb", "gulpfile.js", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Build settings
permalink: none
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  entity_output: numeric

# Podcast settings
lang: de-DE
author: Kai Birkenfeld
copyright: "&#x2117; &amp; &#xA9; 2015"
search: true

# Site owner
owner:
  name: Kai Birkenfeld
  bio:
  avatar: /images/profile.jpg
  email: moin@aethermonolog.de
  twitter: aethermonolog
  facebook: aethermonolog
  youtube: channel/UClOxeAV0iId7gDqwjOeD9_g
  flattr: dyscribe
  disqus: aethermonolog
  soundcloud: klartexter
  spotify: 6oVNztHJaWh9WgyZVMOO4w
  google:
    plus: +KaiBirkenfeld
    verify: XIwbHY2nAqd1Azf8Z3yHwuv1-k8FUlnnm9xQIxJsojQ

# Podcast

podcast:
  source: https://aethermonolog.s3.amazonaws.com/episodes/

# Jekyll plugins
plugins:
 - jekyll-redirect-from
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-sass-converter

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: dyscribe
repo: aethermonolog
branch: master
production_url:  //aethermonolog.de
source_url:      https://github.com/dyscribe/aethermonolog
