# Global site configurations

destination: ../html/aethermonolog.de
title: aethermonolog - Musikproduktion, Homerecording und Musik machen
email: moin@aethermonolog.de
description: "Monologe aus dem Kopf eines Musikers: Was inspiriert? Was blockiert? Was funktioniert? Eine Dokumentation musikalischer Schaffensprozesse."
subtitle: "Lamento ergo sum."
paginate: 5
paginate_path: "posts/:num"
baseurl: ""

# Switch between production and local development
url: https://aethermonolog.de
# url: http://localhost:4000

include: [".htaccess"]

exclude: ["lib", "config.rb", "gulpfile.js", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Build settings
permalink: none
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  entity_output: numeric

# Podcast settings
lang: de-DE
author: Kai Birkenfeld
copyright: "&#x2117; &amp; &#xA9; 2015"

# Site owner
owner:
  name: Kai Birkenfeld
  bio:
  avatar: /images/profile.jpg
  email: moin@aethermonolog.de
  twitter: aethermonolog
  facebook: aethermonolog
  github: dyscribe
  flattr: dyscribe
  disqus: aethermonolog
  soundcloud: klartexter
  google:
    plus: +KaiBirkenfeld
    verify: XIwbHY2nAqd1Azf8Z3yHwuv1-k8FUlnnm9xQIxJsojQ

# Podcast

podcast:
  source: http://aethermonolog.s3-website.eu-central-1.amazonaws.com/episodes/

# Jekyll plugins
gems: [jekyll-mentions, jekyll-redirect-from, jekyll-paginate, jekyll-sitemap, jekyll-sass-converter]

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: dyscribe
repo: aethermonolog
branch: master
production_url:  //aethermonolog.de
source_url:      https://github.com/dyscribe/aethermonolog
