# Global site configurations

destination: ../html/aethermonolog.de
title: aethermonolog.de
email: moin@aethermonolog.de
description: "Die Heimat des aethermonolog Podcasts: Monologe von der Waterkant in den Aether von und mit Kai Birkenfeld."
keywords: ""
paginate: 5
paginate_path: "posts/:num"
baseurl: "/"

# For production
url: http://aethermonolog.de
# For local development
# url: http://localhost:4000

exclude: ["lib", "config.rb", "gulpfile.js", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Build settings
permalink: none
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed

# Podcast settings
lang: de
author: Kai Birkenfeld

# Site owner
owner:
  name: Kai Birkenfeld
  bio:
  avatar:
  email: moin@aethermonolog.de
  disqus-shortname: dyscribe
  twitter: dyscribe
  github: dyscribe
  flattr: dyscribe
  google:
    plus: +KaiBirkenfeld
    verify:

# Podlove Web Player settings
poster: /images/podlove.jpg
alwaysShowHours: true
startVolume: 0.8
width: auto
summaryVisible: false
timecontrolsVisible: false
chaptersVisible: false
sharebuttonsVisible: false

# Jekyll plugins
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-paginate

jekyll-mentions: https://twitter.com
