# Global site configurations

destination: ../html/aethermonolog.de
title: aethermonolog.de
email: moin@aethermonolog.de
description: "Die Heimat des aethermonolog Podcasts: Monologe von der Waterkant in den Aether von und mit Kai Birkenfeld."
baseurl: "/aethermonolog.de/"
url: http://dyscribe.serpens.uberspace.de/aethermonolog.de/
#url: http://localhost:4000
aws_url: podcasts.aethermonolog.de.s3-website.eu-central-1.amazonaws.com
paginate: 5
paginate_path: "posts/:num"

exclude: ["lib", "config.rb", "gulpfile.js", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Build settings
markdown: kramdown
permalink: pretty

# Podcast settings
lang: de
author: Kai Birkenfeld

# Site owner
owner:
  name: Kai Birkenfeld
  bio:
  avatar:
  email: moin@aethermonolog.de
  disqus-shortname: dyscribe
  twitter: dyscribe
  github: dyscribe
  flattr: dyscribe
  google:
    plus: +KaiBirkenfeld
    verify:


# Jekyll plugins
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-paginate

jekyll-mentions: https://twitter.com
